healthcheck

diff --git a/.github/workflows/pipline.yml b/.github/workflows/pipline.yml
--- a/.github/workflows/pipline.yml
+++ b/.github/workflows/pipline.yml
@@ -2,6 +2,8 @@ name: backend-pipeline
 
 env:
     DOCKER_IMAGE_NAME: talel12/backend-session9
+    BACKEND_URL: https://api.demo.lebondeveloppeur.net/
+    HEALTH_PATH: /health
 
 on:
     push:
@@ -338,3 +340,18 @@ jobs:
                       }
                     ]
                   }
+
+    health-check-job:
+      runs-on: ubuntu-latest
+      needs: deploy-to-vps # Run health check only after deployment
+      steps:
+        - name: Health Check - Verify Backend Availability
+          run: |
+            response=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.BACKEND_URL }}${{ env.HEALTH_PATH }}")
+            echo "Received response code: $response"
+            if [ "$response" -ne 200 ]; then
+              echo "Health check failed with response code $response"
+              exit 1
+            else
+              echo "Health check passed successfully!"
+            fi
